name: signalr_pure
description: SignalR Pure is a library which contains some useful tools for Signalr. It's SignalR Client.
version: 1.1.0
homepage: https://github.com/Dimolll/signalr_pure

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  meta: ^1.8.0
  tuple: ^2.0.0

dev_dependencies:
  mockito: ^5.0.16
  lints: ^2.1.1
  test: ^1.16.0
